### PR TITLE
SPM suppport

### PR DESCRIPTION
**Pull request by kenji21**
## Description
Added Package.swift file

## Motivation and Context
integrate this nice piece of code using SPM

## How Has This Been Tested?
building it with `xed .` in repo folder to open the Package.swift "pseudo-project" with in Xcode

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by kenji21** [comment]
related to issue https://github.com/maxep/MXParallaxHeader/issues/116

**Comment by kenji21** [comment]
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.

:/

**Review by maxep — APPROVED** [review]
Thanks @kenji21 👍

**Comment by kenji21** [comment]
One more step in order to have an Xcode project find MXParallaxHeader to be found : it needs a new tag, maybe 1.1.0 should be chosen

**Comment by Drusy** [comment]
Any plan to tag/release this @maxep ?
We now have to target the master branch to use SPM, would be nicer using a release !

**Comment by Drusy** [comment]
Spoke too fast, using the master branch results in missing headers for Swift projects
`Umbrella directory '~/Library/Developer/Xcode/DerivedData/Template-fhwdlwrvaxparjdwvnikcfyarzff/SourcePackages/checkouts/MXParallaxHeader/Sources/include' not found`

**Comment by kenji21** [comment]
Just made a second PR to fix this : https://github.com/maxep/MXParallaxHeader/pull/122

**Pull request merged**
